steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Update staging server
    entrypoint: /bin/sh
    # -c: commands are read from string, set -x: all executed commands are printed to the terminal
    args:
      - "-c"
      - |
        set -x && \
        gcloud compute ssh --zone "asia-southeast1-b" "shorty1"  --project "seventh-sensor-362822" --command='/bin/sh /home/shorty/url-shortener/pull.sh'
