version: "3"
services:
  cassandra:
    container_name: urlshortener-cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./cassandra_data:/var/lib/cassandra

  cassandra-load-keyspace:
    container_name: urlshortener-cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./backend/urlShortener.cql:/urlShortener.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /urlShortener.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  backend:
    container_name: urlshortener-backend
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=cassandra:9042
    depends_on:
      - cassandra
      - cassandra-load-keyspace
